# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://localhost:4000" # the base hostname & protocol for your site
url: "https://brignogan.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: brignogan

# Permalinks
permalink:        pretty

# Build settings
markdown: kramdown

#google analytics
google_analytics: UA-173536521-1
